"""
Regenerates data/*.json caches from SQLite.
Run after any direct DB edits to keep Claude's read caches current.
"""

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.normpath(_os.path.join(_os.path.dirname(__file__), '../../../data')))  # data/ for session files
_sys.path.insert(0, _os.path.normpath(_os.path.join(_os.path.dirname(__file__), '..')))        # src/best_foot_forward/
del _sys, _os

import json
import os
from db import get_conn, DATA_DIR


def _load_bullets() -> list:
    conn = get_conn()

    employers = {r["id"]: r["name"] for r in conn.execute("SELECT id, name FROM employers")}

    bullet_tracks = {}
    for r in conn.execute("SELECT bullet_id, track FROM bullet_tracks"):
        bullet_tracks.setdefault(r["bullet_id"], []).append(r["track"])

    bullet_themes = {}
    for r in conn.execute("SELECT bullet_id, theme FROM bullet_themes"):
        bullet_themes.setdefault(r["bullet_id"], []).append(r["theme"])

    bullets = []
    for r in conn.execute(
        "SELECT b.id, b.employer_id, b.role, b.text, b.use_when FROM bullets b "
        "JOIN employers e ON e.id = b.employer_id ORDER BY e.sort_order, b.rowid"
    ):
        entry = {
            "id":       r["id"],
            "employer": employers[r["employer_id"]],
            "role":     r["role"],
            "text":     r["text"],
            "tracks":   bullet_tracks.get(r["id"], []),
            "themes":   bullet_themes.get(r["id"], []),
        }
        if r["use_when"]:
            entry["use_when"] = r["use_when"]
        bullets.append(entry)

    conn.close()
    return bullets


def export_bullets() -> None:
    bullets = _load_bullets()
    out = {"_notes": "Generated by export_cache.py — edit via SQLite, not this file.", "bullets": bullets}
    with open(os.path.join(DATA_DIR, "_bullets.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(bullets)} bullets → _bullets.json")


def export_bullets_conditional() -> None:
    bullets = _load_bullets()
    conditional = [b for b in bullets if "use_when" in b]

    out = {
        "_notes": "Generated by export_cache.py — conditional bullets (use_when). Load only when the specific condition is met. Edit via SQLite.",
        "bullets": conditional,
    }
    with open(os.path.join(DATA_DIR, "_bullets_conditional.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(conditional)} conditional bullets → _bullets_conditional.json")


def export_skills() -> None:
    conn = get_conn()

    skill_tracks = {}
    for r in conn.execute("SELECT skill_id, track FROM skill_tracks"):
        skill_tracks.setdefault(r["skill_id"], []).append(r["track"])

    skill_themes = {}
    for r in conn.execute("SELECT skill_id, theme FROM skill_themes"):
        skill_themes.setdefault(r["skill_id"], []).append(r["theme"])

    skills = []
    for r in conn.execute("SELECT id, label, content FROM skills ORDER BY rowid"):
        skills.append({
            "id":      r["id"],
            "label":   r["label"],
            "content": r["content"],
            "tracks":  skill_tracks.get(r["id"], []),
            "themes":  skill_themes.get(r["id"], []),
        })

    conn.close()

    out = {
        "_notes": "Generated by export_cache.py — edit via SQLite, not this file. "
                  "Tracks are freeform tags from job history/tailoring (e.g. engineer, manager, architect, founding engineer). Themes match bullets taxonomy.",
        "skills": skills
    }
    with open(os.path.join(DATA_DIR, "_skills.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(skills)} skill groups → _skills.json")


def export_employers() -> None:
    conn = get_conn()
    employers = []
    for r in conn.execute(
        "SELECT id, name, location, start_date, end_date, notes FROM employers ORDER BY sort_order"
    ):
        employers.append({
            "id":         r["id"],
            "name":       r["name"],
            "location":   r["location"],
            "start_date": r["start_date"],
            "end_date":   r["end_date"],
            "notes":      r["notes"],
        })
    conn.close()

    out = {"_notes": "Generated by export_cache.py — edit via SQLite, not this file.", "employers": employers}
    with open(os.path.join(DATA_DIR, "_employers.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(employers)} employers → _employers.json")


def export_contact() -> None:
    conn = get_conn()
    row = conn.execute("SELECT * FROM contact ORDER BY id LIMIT 1").fetchone()
    conn.close()
    if not row:
        print("No contact record found.")
        return
    out = {"_notes": "Generated by export_cache.py — edit via SQLite, not this file.", "contact": dict(row)}
    with open(os.path.join(DATA_DIR, "_contact.json"), "w") as f:
        json.dump(out, f, indent=2)
    print("Exported contact → _contact.json")


def export_education() -> None:
    conn = get_conn()
    rows = conn.execute("SELECT * FROM education ORDER BY sort_order").fetchall()
    conn.close()
    education = [dict(r) for r in rows]
    out = {"_notes": "Generated by export_cache.py — edit via SQLite, not this file.", "education": education}
    with open(os.path.join(DATA_DIR, "_education.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(education)} education record(s) → _education.json")


if __name__ == "__main__":
    export_bullets()
    export_bullets_conditional()
    export_skills()
    export_employers()
    export_contact()
    export_education()
