"""
Regenerates data/application_summaries.json from SQLite.
Exports applications + JDs with tailoring metadata for resume-tailor suggestions and other queryable use cases.
Also refreshes the Applications complete: N line in memory/project_status.md.
"""

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.normpath(_os.path.join(_os.path.dirname(__file__), '../../../data')))  # data/ for session files
_sys.path.insert(0, _os.path.normpath(_os.path.join(_os.path.dirname(__file__), '..')))        # src/best_foot_forward/
del _sys, _os

import json
import os
import re
from datetime import date
from db import get_conn, DATA_DIR


def _load_applications() -> list:
    conn = get_conn()

    rows = conn.execute(
        """SELECT a.id AS app_id, a.jd_id, j.company, j.role, a.status, a.stage,
                  a.applied_at, a.concluded_at, j.score, j.summary,
                  a.source_application_id, a.tailoring_notes, j.output_dir
           FROM applications a
           JOIN jds j ON a.jd_id = j.id
           ORDER BY a.applied_at DESC"""
    ).fetchall()

    applications = []
    for r in rows:
        app = {
            "app_id": r["app_id"],
            "jd_id": r["jd_id"],
            "company": r["company"],
            "role": r["role"],
            "status": r["status"],
            "stage": r["stage"],
            "applied_at": r["applied_at"],
            "score": r["score"],
            "summary": r["summary"],
            "source_application_id": r["source_application_id"],
            "file_path": r["output_dir"],  # materials directory where .docx files live
        }

        # Compute rejected_at and days_to_rejection for rejected applications
        if r["status"] == "rejected" and r["concluded_at"]:
            app["rejected_at"] = r["concluded_at"]
            try:
                applied = date.fromisoformat(r["applied_at"]) if r["applied_at"] else None
                concluded = date.fromisoformat(r["concluded_at"])
                if applied:
                    app["days_to_rejection"] = (concluded - applied).days
            except (ValueError, TypeError):
                pass

        # Include tailoring_notes if present
        if r["tailoring_notes"]:
            app["tailoring_notes"] = r["tailoring_notes"]

        applications.append(app)

    conn.close()
    return applications


def export_applications() -> None:
    applications = _load_applications()
    out = {
        "_notes": "Generated by export_application_summaries.py — contains applications + JDs with tailoring metadata. Edit via SQLite, not this file.",
        "applications": applications
    }
    with open(os.path.join(DATA_DIR, "application_summaries.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"Exported {len(applications)} applications → application_summaries.json")


def refresh_status_greeting() -> None:
    """Refresh the 'Applications complete: N' line in memory/project_status.md."""
    # Claude Code project memory lives under ~/.claude/projects/<slug>/memory/, where
    # <slug> is the project root's absolute path with os.sep replaced by '-'.
    project_root = os.path.dirname(DATA_DIR)
    slug = project_root.replace(os.sep, '-')
    home = os.path.expanduser("~")
    memory_file = os.path.join(home, ".claude", "projects", slug, "memory", "project_status.md")

    # Fall back to a project-relative memory/ dir (e.g. a symlink), if present instead
    if not os.path.exists(memory_file):
        local_memory_file = os.path.join(project_root, "memory", "project_status.md")
        if os.path.exists(local_memory_file):
            memory_file = local_memory_file

    if not os.path.exists(memory_file):
        print(f"⚠ memory/project_status.md not found at {memory_file}; skipping greeting refresh")
        return

    # Count applied applications
    conn = get_conn()
    count = conn.execute("SELECT COUNT(*) as n FROM applications WHERE applied_at IS NOT NULL").fetchone()["n"]
    conn.close()

    # Read the file and replace the count line
    try:
        with open(memory_file, "r") as f:
            content = f.read()
    except Exception as e:
        print(f"⚠ Could not read {memory_file}: {e}")
        return

    # Replace only the "Applications complete: N" line
    new_content = re.sub(
        r"^Applications complete: \d+$",
        f"Applications complete: {count}",
        content,
        count=1,
        flags=re.MULTILINE
    )

    if new_content == content:
        # Line either doesn't exist or is already at the correct count — both cases are fine, just skip silently
        return

    try:
        with open(memory_file, "w") as f:
            f.write(new_content)
        print(f"Refreshed greeting: Applications complete: {count}")
    except Exception as e:
        print(f"⚠ Could not write to {memory_file}: {e}")


if __name__ == "__main__":
    export_applications()
    refresh_status_greeting()
